# Server Port (Runs on port 8080 by default)
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://ep-royal-shape-axkkf9cm-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nkj7FhaSIL3g
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings (Auto-creates your database tables based on your Java entities)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: OAuth2 Credentials placeholders (You will get these from Google Cloud Console later)
# spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
# spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET

spring.security.oauth2.client.registration.github.client-id=Ov23lilKcbCP4MAvaz6n
spring.security.oauth2.client.registration.github.client-secret=96509f6c2736cd7bf0622d95933c125b89e82826

  

spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.registration.github.client-name=GitHub
spring.security.oauth2.client.registration.github.redirect-uri=https://cautious-giggle-5gvq9v4xxq4jf4xjr-8080.app.github.dev/login/oauth2/code/github

server.forward-headers-strategy=framework
frontend.url=https://cautious-giggle-5gvq9v4xxq4jf4xjr-5173.app.github.dev/


